version: '3.6'

services:
  custompios:
    image: guysoft/custompios:devel
    container_name: photoprismpi-build
    tty: true
    restart: always
    privileged: true
    volumes:
      - ./:/distro
    devices:
      - /dev/loop-control

